require('dotenv').config();

const { defineConfig } = require("cypress");
// import { resetDb } from './cypress/tasks/resetDb'

module.exports = defineConfig({
  // projectId: 'nw3enx', // Generated by Cypress Cloud.
  projectId: process.env.CYPRESS_PROJECT_ID, // Using dotenv library
  viewportHeight: 550,
  viewportWidth: 660,
  // video: true, // Video will be made in headless tests only.

  e2e: {
    // setupNodeEvents(on: Cypress.PluginEvents, config: Cypress.PluginConfigOptions) {
    //
    //   /* lesson 18 - Task. */
    //   // on('task', {
    //   //   reset: resetDb
    //   // })
    //
    //   /* lesson 19 - Config. */
    //   // config.baseUrl = process.env.CI ? 'https://skillmea.sk' : 'http://localhost:3000'
    //   // return config
    // },
    specPattern: '**/headless/*.cy.{js,ts}',
    // excludeSpecPattern: '**/headless/*.cy.{js,ts}',

    baseUrl: 'http://localhost:3000',
    // experimentalWebKitSupport: true,

    allowCypressEnv: false,

    /* Test environment variables */
    // env: {
    //   requestMode: true
    // }

    // retries: 1 // Number of retries for failed tests
  }
});
